const variantList = [
  "Front",
  "Rear",
  "Front Right",
  "Front Left",
  "Rear Right",
  "Rear Left",
  "Upper Front Right",
  "Upper Front Left",
  "Upper Rear Right",
  "Upper Rear Left",
  "Lower Front Right",
  "Lower Front Left",
  "Lower Rear Right",
  "Lower Rear Left",
]; // just for variant input

const makeList = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Ferrari",
  "FIAT",
  "Fisker",
  "Ford",
  "Freightliner",
  "Genesis",
  "Geo",
  "GMC",
  "Honda",
  "HUMMER",
  "Hyundai",
  "INFINITI",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Lucid",
  "Maserati",
  "Maybach",
  "MAZDA",
  "McLaren",
  "Mercedes-Benz",
  "Mercury",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Oldsmobile",
  "Plymouth",
  "Polestar",
  "Pontiac",
  "Porsche",
  "Ram",
  "Rivian",
  "Rolls-Royce",
  "Saab",
  "Saturn",
  "Scion",
  "Smart",
  "SRT",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "VinFast",
  "Volkswagen",
  "Volvo",
];

const modelList = [
  "CL",
  "ILX",
  "Integra",
  "Legend",
  "MDX",
  "MDX Sport Hybrid",
  "NSX",
  "RDX",
  "RL",
  "RLX",
  "RLX Sport Hybrid",
  "RSX",
  "SLX",
  "TL",
  "TLX",
  "TSX",
  "Vigor",
  "ZDX",
  "164",
  "4C",
  "4C Spider",
  "Giulia",
  "Spider",
  "Stelvio",
  "Tonale",
  "DB11",
  "DB9",
  "DB9 GT",
  "DBS",
  "DBS Superleggera",
  "DBX",
  "Rapide",
  "Rapide S",
  "Vanquish",
  "Vanquish S",
  "Vantage",
  "Virage",
  "100",
  "80",
  "90",
  "A3",
  "A3 Sportback e-tron",
  "A4",
  "A4 (2005.5)",
  "A4 allroad",
  "A5",
  "A5 Sport",
  "A6",
  "A6 allroad",
  "A7",
  "A8",
  "allroad",
  "Cabriolet",
  "e-tron",
  "e-tron GT",
  "e-tron S",
  "e-tron S Sportback",
  "e-tron Sportback",
  "Q3",
  "Q4 e-tron",
  "Q4 Sportback e-tron",
  "Q5",
  "Q5 Sportback",
  "Q6 e-tron",
  "Q7",
  "Q8",
  "Q8 e-tron",
  "Q8 Sportback e-tron",
  "Quattro",
  "R8",
  "RS 3",
  "RS 4",
  "RS 5",
  "RS 6",
  "RS 7",
  "RS e-tron GT",
  "RS Q8",
  "S3",
  "S4",
  "S4 (2005.5)",
  "S5",
  "S6",
  "S7",
  "S8",
  "SQ5",
  "SQ5 Sportback",
  "SQ7",
  "SQ8",
  "SQ8 e-tron",
  "SQ8 Sportback e-tron",
  "TT",
  "Arnage",
  "Azure",
  "Azure T",
  "Bentayga",
  "Brooklands",
  "Continental",
  "Continental GT",
  "Flying Spur",
  "Mulsanne",
  "1 Series",
  "2 Series",
  "3 Series",
  "4 Series",
  "5 Series",
  "6 Series",
  "7 Series",
  "8 Series",
  "Alpina B7",
  "i3",
  "i4",
  "i5",
  "i7",
  "i8",
  "iX",
  "M",
  "M2",
  "M3",
  "M4",
  "M5",
  "M6",
  "M8",
  "X1",
  "X2",
  "X3",
  "X3 M",
  "X4",
  "X4 M",
  "X5",
  "X5 M",
  "X6",
  "X6 M",
  "X7",
  "XM",
  "Z3",
  "Z4",
  "Z4 M",
  "Z8",
  "Cascada",
  "Century",
  "Enclave",
  "Encore",
  "Encore GX",
  "Envision",
  "Envista",
  "LaCrosse",
  "LeSabre",
  "Lucerne",
  "Park Avenue",
  "Rainier",
  "Regal",
  "Regal Sportback",
  "Regal TourX",
  "Rendezvous",
  "Riviera",
  "Roadmaster",
  "Skylark",
  "Terraza",
  "Verano",
  "Allante",
  "ATS",
  "ATS-V",
  "Brougham",
  "Catera",
  "Celestiq",
  "CT4",
  "CT5",
  "CT6",
  "CT6-V",
  "CTS",
  "CTS-V",
  "DeVille",
  "DTS",
  "Eldorado",
  "ELR",
  "Escalade",
  "Escalade ESV",
  "Escalade EXT",
  "Escalade IQ",
  "Fleetwood",
  "LYRIQ",
  "OPTIQ",
  "Seville",
  "Sixty Special",
  "SRX",
  "STS",
  "Vistiq",
  "XLR",
  "XT4",
  "XT5",
  "XT6",
  "XTS",
  "1500 Extended Cab",
  "1500 Regular Cab",
  "2500 Crew Cab",
  "2500 Extended Cab",
  "2500 HD Extended Cab",
  "2500 HD Regular Cab",
  "2500 Regular Cab",
  "3500 Crew Cab",
  "3500 Extended Cab",
  "3500 HD Extended Cab",
  "3500 HD Regular Cab",
  "3500 Regular Cab",
  "APV Cargo",
  "Astro Cargo",
  "Astro Passenger",
  "Avalanche",
  "Avalanche 1500",
  "Avalanche 2500",
  "Aveo",
  "Beretta",
  "Blazer",
  "Blazer EV",
  "Bolt EUV",
  "Bolt EV",
  "Camaro",
  "Caprice",
  "Caprice Classic",
  "Captiva Sport",
  "Cavalier",
  "City Express",
  "Classic",
  "Cobalt",
  "Colorado Crew Cab",
  "Colorado Extended Cab",
  "Colorado Regular Cab",
  "Corsica",
  "Corvette",
  "Cruze",
  "Cruze Limited",
  "Equinox",
  "Equinox EV",
  "Express 1500 Cargo",
  "Express 1500 Passenger",
  "Express 2500 Cargo",
  "Express 2500 Passenger",
  "Express 3500 Cargo",
  "Express 3500 Passenger",
  "G-Series 1500",
  "G-Series 2500",
  "G-Series 3500",
  "G-Series G10",
  "G-Series G20",
  "G-Series G30",
  "HHR",
  "Impala",
  "Impala Limited",
  "Lumina",
  "Lumina APV",
  "Lumina Cargo",
  "Lumina Passenger",
  "Malibu",
  "Malibu (Classic)",
  "Malibu Limited",
  "Metro",
  "Monte Carlo",
  "Prizm",
  "S10 Blazer",
  "S10 Crew Cab",
  "S10 Extended Cab",
  "S10 Regular Cab",
  "Silverado (Classic) 1500 Crew Cab",
  "Silverado (Classic) 1500 Extended Cab",
  "Silverado (Classic) 1500 HD Crew Cab",
  "Silverado (Classic) 1500 Regular Cab",
  "Silverado (Classic) 2500 HD Crew Cab",
  "Silverado (Classic) 2500 HD Extended Cab",
  "Silverado (Classic) 2500 HD Regular Cab",
  "Silverado (Classic) 3500 Crew Cab",
  "Silverado (Classic) 3500 Extended Cab",
  "Silverado (Classic) 3500 Regular Cab",
  "Silverado 1500 Crew Cab",
  "Silverado 1500 Double Cab",
  "Silverado 1500 Extended Cab",
  "Silverado 1500 HD Crew Cab",
  "Silverado 1500 LD Double Cab",
  "Silverado 1500 Limited Crew Cab",
  "Silverado 1500 Limited Double Cab",
  "Silverado 1500 Limited Regular Cab",
  "Silverado 1500 Regular Cab",
  "Silverado 2500 Crew Cab",
  "Silverado 2500 Extended Cab",
  "Silverado 2500 HD Crew Cab",
  "Silverado 2500 HD Double Cab",
  "Silverado 2500 HD Extended Cab",
  "Silverado 2500 HD Regular Cab",
  "Silverado 2500 Regular Cab",
  "Silverado 3500 Crew Cab",
  "Silverado 3500 Extended Cab",
  "Silverado 3500 HD Crew Cab",
  "Silverado 3500 HD Double Cab",
  "Silverado 3500 HD Extended Cab",
  "Silverado 3500 HD Regular Cab",
  "Silverado 3500 Regular Cab",
  "Silverado EV",
  "Sonic",
  "Spark",
  "Spark EV",
  "Sportvan G10",
  "Sportvan G20",
  "Sportvan G30",
  "SS",
  "SSR",
  "Suburban",
  "Suburban 1500",
  "Suburban 2500",
  "Suburban 3500HD",
  "Tahoe",
  "Tahoe (New)",
  "Tracker",
  "TrailBlazer",
  "Traverse",
  "Traverse Limited",
  "Trax",
  "Uplander Cargo",
  "Uplander Passenger",
  "Venture Cargo",
  "Venture Passenger",
  "Volt",
  "200",
  "300",
  "300M",
  "Aspen",
  "Cirrus",
  "Concorde",
  "Crossfire",
  "Fifth Ave",
  "Grand Voyager",
  "Imperial",
  "LeBaron",
  "LHS",
  "New Yorker",
  "Pacifica",
  "Pacifica Hybrid",
  "Prowler",
  "PT Cruiser",
  "Sebring",
  "Town & Country",
  "Voyager",
  "Avenger",
  "Caliber",
  "Caravan Cargo",
  "Caravan Passenger",
  "Challenger",
  "Charger",
  "Colt",
  "D150 Club Cab",
  "D150 Regular Cab",
  "D250 Club Cab",
  "D250 Regular Cab",
  "D350 Club Cab",
  "D350 Regular Cab",
  "Dakota Club Cab",
  "Dakota Crew Cab",
  "Dakota Extended Cab",
  "Dakota Quad Cab",
  "Dakota Regular Cab",
  "Dart",
  "Daytona",
  "Durango",
  "Dynasty",
  "Grand Caravan Cargo",
  "Grand Caravan Passenger",
  "Hornet",
  "Intrepid",
  "Journey",
  "Magnum",
  "Monaco",
  "Neon",
  "Nitro",
  "Ram 1500 Club Cab",
  "Ram 1500 Crew Cab",
  "Ram 1500 Mega Cab",
  "Ram 1500 Quad Cab",
  "Ram 1500 Regular Cab",
  "Ram 2500 Club Cab",
  "Ram 2500 Crew Cab",
  "Ram 2500 Mega Cab",
  "Ram 2500 Quad Cab",
  "Ram 2500 Regular Cab",
  "Ram 3500 Club Cab",
  "Ram 3500 Crew Cab",
  "Ram 3500 Mega Cab",
  "Ram 3500 Quad Cab",
  "Ram 3500 Regular Cab",
  "Ram 50 Regular Cab",
  "Ram Van 1500",
  "Ram Van 2500",
  "Ram Van 3500",
  "Ram Van B150",
  "Ram Van B250",
  "Ram Van B350",
  "Ram Wagon 1500",
  "Ram Wagon 2500",
  "Ram Wagon 3500",
  "Ram Wagon B150",
  "Ram Wagon B250",
  "Ram Wagon B350",
  "Ramcharger",
  "Shadow",
  "Spirit",
  "Sprinter 2500 Cargo",
  "Sprinter 2500 Passenger",
  "Sprinter 3500 Cargo",
  "Stealth",
  "Stratus",
  "Viper",
  "296 GTB",
  "430 Scuderia",
  "458 Italia",
  "458 Speciale",
  "458 Spider",
  "488 GTB",
  "488 Pista",
  "488 Spider",
  "599 GTB Fiorano",
  "599 GTO",
  "612 Scaglietti",
  "812 Competizione",
  "812 Competizione A",
  "812 GTS",
  "812 Superfast",
  "California",
  "F12berlinetta",
  "F430",
  "F8",
  "FF",
  "GTC4Lusso",
  "Portofino",
  "Roma",
  "SF90",
  "124 Spider",
  "500",
  "500 Abarth",
  "500c",
  "500c Abarth",
  "500e",
  "500L",
  "500X",
  "Alaska",
  "Karma",
  "Ocean",
  "Pear",
  "Ronin",
  "Aerostar Cargo",
  "Aerostar Passenger",
  "Aspire",
  "Bronco",
  "Bronco Sport",
  "C-MAX Energi",
  "C-MAX Hybrid",
  "Club Wagon",
  "Contour",
  "Crown Victoria",
  "E-Transit 350 Cargo Van",
  "E150 Cargo",
  "E150 Passenger",
  "E150 Super Duty Cargo",
  "E150 Super Duty Passenger",
  "E250 Cargo",
  "E250 Super Duty Cargo",
  "E350 Super Duty Cargo",
  "E350 Super Duty Passenger",
  "Econoline E150 Cargo",
  "Econoline E150 Passenger",
  "Econoline E250 Cargo",
  "Econoline E350 Cargo",
  "Econoline E350 Super Duty Cargo",
  "Econoline E350 Super Duty Passenger",
  "EcoSport",
  "Edge",
  "Escape",
  "Escape Plug-in Hybrid",
  "Escort",
  "Excursion",
  "Expedition",
  "Expedition EL",
  "Expedition MAX",
  "Explorer",
  "Explorer Sport",
  "Explorer Sport Trac",
  "F150 (Heritage) Regular Cab",
  "F150 (Heritage) Super Cab",
  "F150 Lightning",
  "F150 Regular Cab",
  "F150 Super Cab",
  "F150 SuperCrew Cab",
  "F250 Crew Cab",
  "F250 Regular Cab",
  "F250 Super Cab",
  "F250 Super Duty Crew Cab",
  "F250 Super Duty Regular Cab",
  "F250 Super Duty Super Cab",
  "F350 Crew Cab",
  "F350 Regular Cab",
  "F350 Super Cab",
  "F350 Super Duty Crew Cab",
  "F350 Super Duty Regular Cab",
  "F350 Super Duty Super Cab",
  "F450 Super Duty Crew Cab",
  "F450 Super Duty Regular Cab",
  "Festiva",
  "Fiesta",
  "Five Hundred",
  "Flex",
  "Focus",
  "Focus ST",
  "Freestar Cargo",
  "Freestar Passenger",
  "Freestyle",
  "Fusion",
  "Fusion Energi",
  "Fusion Plug-in Hybrid",
  "GT",
  "Maverick",
  "Mustang",
  "Mustang MACH-E",
  "Probe",
  "Ranger Regular Cab",
  "Ranger Super Cab",
  "Ranger SuperCab",
  "Ranger SuperCrew",
  "Taurus",
  "Taurus X",
  "Tempo",
  "Thunderbird",
  "Transit 150 Cargo Van",
  "Transit 150 Crew Van",
  "Transit 150 Passenger Van",
  "Transit 150 Van",
  "Transit 150 Wagon",
  "Transit 250 Cargo Van",
  "Transit 250 Crew Van",
  "Transit 250 Van",
  "Transit 350 Cargo Van",
  "Transit 350 Crew Van",
  "Transit 350 HD Cargo Van",
  "Transit 350 HD Crew Van",
  "Transit 350 HD Van",
  "Transit 350 Passenger Van",
  "Transit 350 Van",
  "Transit 350 Wagon",
  "Transit Connect Cargo",
  "Transit Connect Cargo Van",
  "Transit Connect Passenger",
  "Transit Connect Passenger Wagon",
  "Windstar Cargo",
  "Windstar Passenger",
  "ZX2",
  "Sprinter 1500 Cargo",
  "Sprinter 1500 Passenger",
  "Sprinter 2500 Cargo",
  "Sprinter 2500 Crew",
  "Sprinter 2500 Passenger",
  "Sprinter 3500 Cargo",
  "Sprinter 3500 Crew",
  "Sprinter 3500 XD Crew",
  "Sprinter 3500XD Cargo",
  "Sprinter 4500 Cargo",
  "Sprinter 4500 Crew",
  "Sprinter WORKER Cargo",
  "Sprinter WORKER Passenger",
  "Electrified G80",
  "Electrified GV70",
  "G70",
  "G80",
  "G90",
  "GV60",
  "GV70",
  "GV80",
  "GV80 Coupe",
  "Metro",
  "Prizm",
  "Storm",
  "Tracker",
  "1500 Club Coupe",
  "1500 Regular Cab",
  "2500 Club Coupe",
  "2500 Crew Cab",
  "2500 HD Club Coupe",
  "2500 HD Extended Cab",
  "2500 HD Regular Cab",
  "2500 Regular Cab",
  "3500 Club Coupe",
  "3500 Crew Cab",
  "3500 Extended Cab",
  "3500 Regular Cab",
  "Acadia",
  "Acadia Limited",
  "Canyon Crew Cab",
  "Canyon Extended Cab",
  "Canyon Regular Cab",
  "Envoy",
  "Envoy XL",
  "Envoy XUV",
  "HUMMER EV Pickup",
  "HUMMER EV SUV",
  "Jimmy",
  "Rally Wagon 1500",
  "Rally Wagon 2500",
  "Rally Wagon 3500",
  "Rally Wagon G2500",
  "Rally Wagon G3500",
  "Safari Cargo",
  "Safari Passenger",
  "Savana 1500 Cargo",
  "Savana 1500 Passenger",
  "Savana 2500 Cargo",
  "Savana 2500 Passenger",
  "Savana 3500 Cargo",
  "Savana 3500 Passenger",
  "Sierra (Classic) 1500 Crew Cab",
  "Sierra (Classic) 1500 Extended Cab",
  "Sierra (Classic) 1500 HD Crew Cab",
  "Sierra (Classic) 1500 Regular Cab",
  "Sierra (Classic) 2500 Crew Cab",
  "Sierra (Classic) 2500 HD Crew Cab",
  "Sierra (Classic) 2500 HD Extended Cab",
  "Sierra (Classic) 2500 HD Regular Cab",
  "Sierra (Classic) 3500 Crew Cab",
  "Sierra (Classic) 3500 Extended Cab",
  "Sierra (Classic) 3500 Regular Cab",
  "Sierra 1500 Crew Cab",
  "Sierra 1500 Double Cab",
  "Sierra 1500 Extended Cab",
  "Sierra 1500 HD Crew Cab",
  "Sierra 1500 Limited Crew Cab",
  "Sierra 1500 Limited Double Cab",
  "Sierra 1500 Limited Regular Cab",
  "Sierra 1500 Regular Cab",
  "Sierra 2500 Crew Cab",
  "Sierra 2500 Extended Cab",
  "Sierra 2500 HD Crew Cab",
  "Sierra 2500 HD Double Cab",
  "Sierra 2500 HD Extended Cab",
  "Sierra 2500 HD Regular Cab",
  "Sierra 2500 Regular Cab",
  "Sierra 3500 Crew Cab",
  "Sierra 3500 Extended Cab",
  "Sierra 3500 HD Crew Cab",
  "Sierra 3500 HD Double Cab",
  "Sierra 3500 HD Extended Cab",
  "Sierra 3500 HD Regular Cab",
  "Sierra 3500 Regular Cab",
  "Sierra EV",
  "Sonoma Club Cab",
  "Sonoma Club Coupe Cab",
  "Sonoma Crew Cab",
  "Sonoma Extended Cab",
  "Sonoma Regular Cab",
  "Suburban 1500",
  "Suburban 2500",
  "Terrain",
  "Vandura 1500",
  "Vandura 2500",
  "Vandura 3500",
  "Vandura G1500",
  "Vandura G2500",
  "Vandura G3500",
  "Yukon",
  "Yukon Denali",
  "Yukon XL",
  "Yukon XL 1500",
  "Yukon XL 2500",
  "Accord",
  "Accord Crosstour",
  "Accord Hybrid",
  "Civic",
  "Civic Type R",
  "Clarity Electric",
  "Clarity Fuel Cell",
  "Clarity Plug-in Hybrid",
  "CR-V",
  "CR-V Hybrid",
  "CR-Z",
  "Crosstour",
  "del Sol",
  "Element",
  "Fit",
  "HR-V",
  "Insight",
  "Odyssey",
  "Passport",
  "Pilot",
  "Prelude",
  "Prologue",
  "Ridgeline",
  "S2000",
  "H1",
  "H2",
  "H3",
  "H3T",
  "Accent",
  "Azera",
  "Elantra",
  "Elantra GT",
  "Elantra Hybrid",
  "Elantra N",
  "Entourage",
  "Equus",
  "Excel",
  "Genesis",
  "Genesis Coupe",
  "IONIQ 5",
  "IONIQ 6",
  "IONIQ 7",
  "Ioniq Electric",
  "Ioniq Hybrid",
  "Ioniq Plug-in Hybrid",
  "Kona",
  "Kona Electric",
  "Kona N",
  "NEXO",
  "Palisade",
  "Santa Cruz",
  "Santa Fe",
  "Santa Fe Hybrid",
  "Santa Fe Plug-in Hybrid",
  "Santa Fe Sport",
  "Santa Fe XL",
  "Scoupe",
  "Sonata",
  "Sonata Hybrid",
  "Sonata Plug-in Hybrid",
  "Tiburon",
  "Tucson",
  "Tucson Fuel Cell",
  "Tucson Hybrid",
  "Tucson Plug-in Hybrid",
  "Veloster",
  "Venue",
  "Veracruz",
  "XG300",
  "XG350",
  "EX",
  "FX",
  "G",
  "I",
  "J",
  "JX",
  "M",
  "Q",
  "Q40",
  "Q50",
  "Q60",
  "Q70",
  "QX",
  "QX30",
  "QX50",
  "QX55",
  "QX60",
  "QX70",
  "QX80",
  "Amigo",
  "Ascender",
  "Axiom",
  "Hombre Regular Cab",
  "Hombre Spacecab",
  "i-280 Extended Cab",
  "i-290 Extended Cab",
  "i-350 Crew Cab",
  "i-370 Crew Cab",
  "i-370 Extended Cab",
  "Impulse",
  "Oasis",
  "Regular Cab",
  "Rodeo",
  "Rodeo Sport",
  "Spacecab",
  "Stylus",
  "Trooper",
  "VehiCROSS",
  "E-PACE",
  "F-PACE",
  "F-TYPE",
  "I-PACE",
  "S-Type",
  "X-Type",
  "XE",
  "XF",
  "XJ",
  "XK",
  "Cherokee",
  "Comanche Regular Cab",
  "Commander",
  "Compass",
  "Gladiator",
  "Grand Cherokee",
  "Grand Cherokee 4xe",
  "Grand Cherokee L",
  "Grand Wagoneer",
  "Grand Wagoneer L",
  "Liberty",
  "Patriot",
  "Recon",
  "Renegade",
  "Wagoneer",
  "Wagoneer L",
  "Wrangler",
  "Wrangler 2 Door",
  "Wrangler 4 Door",
  "Wrangler 4xe",
  "Wrangler Unlimited",
  "Wrangler Unlimited 4xe",
  "Amanti",
  "Borrego",
  "Cadenza",
  "Carnival",
  "EV6",
  "EV9",
  "Forte",
  "Forte Koup",
  "Forte5",
  "K5",
  "K900",
  "Niro",
  "Niro EV",
  "Niro Plug-in Hybrid",
  "Optima",
  "Optima (2006.5)",
  "Optima Hybrid",
  "Optima Plug-in Hybrid",
  "Rio",
  "Rondo",
  "Sedona",
  "Seltos",
  "Sephia",
  "Sorento",
  "Sorento Hybrid",
  "Sorento Plug-in Hybrid",
  "Soul",
  "Soul EV",
  "Spectra",
  "Sportage",
  "Sportage Hybrid",
  "Sportage Plug-in Hybrid",
  "Stinger",
  "Telluride",
  "Aventador",
  "Gallardo",
  "Huracan",
  "Murcielago",
  "Murcielago LP640",
  "Urus",
  "Defender 110",
  "Defender 130",
  "Defender 90",
  "Discovery",
  "Discovery Series II",
  "Discovery Sport",
  "Freelander",
  "LR2",
  "LR3",
  "LR4",
  "Range Rover",
  "Range Rover Evoque",
  "Range Rover Sport",
  "Range Rover Velar",
  "CT",
  "ES",
  "GS",
  "GX",
  "HS",
  "IS",
  "IS F",
  "LC",
  "LFA",
  "LS",
  "LX",
  "NX",
  "RC",
  "RX",
  "RZ",
  "SC",
  "TX",
  "UX",
  "Aviator",
  "Blackwood",
  "Continental",
  "Corsair",
  "LS",
  "Mark LT",
  "Mark VII",
  "Mark VIII",
  "MKC",
  "MKS",
  "MKT",
  "MKX",
  "MKZ",
  "Nautilus",
  "Navigator",
  "Navigator L",
  "Town Car",
  "Zephyr",
  "Elise",
  "Evora",
  "Evora 400",
  "Evora GT",
  "Exige",
  "Exige S",
  "Air",
  "Gravity",
  "Coupe",
  "Ghibli",
  "GranSport",
  "GranTurismo",
  "Grecale",
  "Levante",
  "MC20",
  "Quattroporte",
  "57",
  "62",
  "323",
  "626",
  "929",
  "B-Series Cab Plus",
  "B-Series Extended Cab",
  "B-Series Regular Cab",
  "CX-3",
  "CX-30",
  "CX-5",
  "CX-50",
  "CX-7",
  "CX-70",
  "CX-9",
  "CX-90",
  "CX-90 PHEV",
  "MAZDA2",
  "MAZDA3",
  "MAZDA5",
  "MAZDA6",
  "Millenia",
  "MPV",
  "MX-3",
  "MX-30",
  "MX-5 Miata",
  "MX-5 Miata RF",
  "MX-6",
  "Navajo",
  "Protege",
  "Protege5",
  "RX-7",
  "RX-8",
  "Tribute",
  "570GT",
  "570S",
  "600LT",
  "650S",
  "675LT",
  "720S",
  "MP4-12C",
  "190 E",
  "300 CE",
  "300 D",
  "300 E",
  "300 SD",
  "300 SE",
  "300 SL",
  "300 TE",
  "400 E",
  "400 SE",
  "400 SEL",
  "500 E",
  "500 SEC",
  "500 SEL",
  "500 SL",
  "600 SEC",
  "600 SEL",
  "600 SL",
  "A-Class",
  "B-Class",
  "C-Class",
  "CL-Class",
  "CLA",
  "CLA-Class",
  "CLE",
  "CLK-Class",
  "CLS",
  "CLS-Class",
  "E-Class",
  "eSprinter",
  "G-Class",
  "GL-Class",
  "GLA",
  "GLA-Class",
  "GLB",
  "GLC",
  "GLC Coupe",
  "GLE",
  "GLE Coupe",
  "GLK-Class",
  "GLS",
  "M-Class",
  "Mercedes-AMG A-Class",
  "Mercedes-AMG C-Class",
  "Mercedes-AMG CLA",
  "Mercedes-AMG CLS",
  "Mercedes-AMG E-Class",
  "Mercedes-AMG EQE",
  "Mercedes-AMG EQE SUV",
  "Mercedes-AMG EQS",
  "Mercedes-AMG G-Class",
  "Mercedes-AMG GLA",
  "Mercedes-AMG GLB",
  "Mercedes-AMG GLC",
  "Mercedes-AMG GLC Coupe",
  "Mercedes-AMG GLE",
  "Mercedes-AMG GLE Coupe",
  "Mercedes-AMG GLS",
  "Mercedes-AMG GT",
  "Mercedes-AMG S-Class",
  "Mercedes-AMG SL",
  "Mercedes-AMG SLC",
  "Mercedes-AMG SLK",
  "Mercedes-EQ EQB",
  "Mercedes-EQ EQE",
  "Mercedes-EQ EQE SUV",
  "Mercedes-EQ EQS",
  "Mercedes-EQ EQS SUV",
  "Mercedes-Maybach EQS SUV",
  "Mercedes-Maybach GLS",
  "Mercedes-Maybach S 600",
  "Mercedes-Maybach S-Class",
  "Metris Cargo",
  "Metris Passenger",
  "Metris WORKER Cargo",
  "Metris WORKER Passenger",
  "R-Class",
  "S-Class",
  "SL",
  "SL-Class",
  "SLC",
  "SLK",
  "SLK-Class",
  "SLR McLaren",
  "SLS-Class",
  "Sprinter 1500 Cargo",
  "Sprinter 1500 Passenger",
  "Sprinter 2500 Cargo",
  "Sprinter 2500 Crew",
  "Sprinter 2500 Passenger",
  "Sprinter 3500 Cargo",
  "Sprinter 3500 Crew",
  "Sprinter 3500 XD Cargo",
  "Sprinter 3500 XD Crew",
  "Sprinter 4500 Cargo",
  "Sprinter 4500 Crew",
  "Sprinter WORKER Cargo",
  "Sprinter WORKER Passenger",
  "Capri",
  "Cougar",
  "Grand Marquis",
  "Marauder",
  "Mariner",
  "Milan",
  "Montego",
  "Monterey",
  "Mountaineer",
  "Mystique",
  "Sable",
  "Topaz",
  "Tracer",
  "Villager",
  "Clubman",
  "Convertible",
  "Cooper",
  "Countryman",
  "Coupe",
  "Hardtop",
  "Hardtop 2 Door",
  "Hardtop 4 Door",
  "Paceman",
  "Roadster",
  "3000GT",
  "Diamante",
  "Eclipse",
  "Eclipse Cross",
  "Endeavor",
  "Expo",
  "Galant",
  "i-MiEV",
  "Lancer",
  "Lancer Evolution",
  "Mighty Max Macro Cab",
  "Mighty Max Regular Cab",
  "Mirage",
  "Mirage G4",
  "Montero",
  "Montero Sport",
  "Outlander",
  "Outlander PHEV",
  "Outlander Sport",
  "Precis",
  "Raider Double Cab",
  "Raider Extended Cab",
  "200SX",
  "240SX",
  "300ZX",
  "350Z",
  "370Z",
  "400Z",
  "Altima",
  "Ariya",
  "Armada",
  "cube",
  "Frontier Crew Cab",
  "Frontier King Cab",
  "Frontier Regular Cab",
  "GT-R",
  "JUKE",
  "Kicks",
  "King Cab",
  "LEAF",
  "Maxima",
  "Murano",
  "NV1500 Cargo",
  "NV200",
  "NV200 Taxi",
  "NV2500 HD Cargo",
  "NV3500 HD Cargo",
  "NV3500 HD Passenger",
  "NX",
  "Pathfinder",
  "Pathfinder Armada",
  "Quest",
  "Regular Cab",
  "Rogue",
  "Rogue Select",
  "Rogue Sport",
  "Sentra",
  "Stanza",
  "Titan Crew Cab",
  "Titan King Cab",
  "TITAN Single Cab",
  "TITAN XD Crew Cab",
  "TITAN XD King Cab",
  "TITAN XD Single Cab",
  "Versa",
  "Versa Note",
  "Xterra",
  "Z",
  "88",
  "98",
  "Achieva",
  "Alero",
  "Aurora",
  "Bravada",
  "Ciera",
  "Custom Cruiser",
  "Cutlass",
  "Cutlass Ciera",
  "Cutlass Cruiser",
  "Cutlass Supreme",
  "Intrigue",
  "LSS",
  "Regency",
  "Silhouette",
  "Toronado",
  "Acclaim",
  "Breeze",
  "Colt",
  "Colt Vista",
  "Grand Voyager",
  "Laser",
  "Neon",
  "Prowler",
  "Sundance",
  "Voyager",
  "1",
  "2",
  "3",
  "4",
  "5",
  "Aztek",
  "Bonneville",
  "Firebird",
  "G3",
  "G5",
  "G6",
  "G6 (2009.5)",
  "G8",
  "Grand Am",
  "Grand Prix",
  "GTO",
  "LeMans",
  "Montana",
  "Montana SV6",
  "Solstice",
  "Sunbird",
  "Sunfire",
  "Torrent",
  "Trans Sport",
  "Vibe",
  "718 Boxster",
  "718 Cayman",
  "718 Spyder",
  "911",
  "928",
  "968",
  "Boxster",
  "Carrera GT",
  "Cayenne",
  "Cayenne Coupe",
  "Cayman",
  "Macan",
  "Panamera",
  "Taycan",
  "Taycan Cross Turismo",
  "Taycan Sport Turismo",
  "1500 Classic Crew Cab",
  "1500 Classic Quad Cab",
  "1500 Classic Regular Cab",
  "1500 Crew Cab",
  "1500 Quad Cab",
  "1500 Ramcharger",
  "1500 Regular Cab",
  "1500 REV",
  "2500 Crew Cab",
  "2500 Mega Cab",
  "2500 Regular Cab",
  "3500 Crew Cab",
  "3500 Mega Cab",
  "3500 Regular Cab",
  "C/V",
  "C/V Tradesman",
  "Dakota Crew Cab",
  "Dakota Extended Cab",
  "ProMaster 1500 Cargo",
  "ProMaster 2500 Cargo",
  "ProMaster 3500 Cargo",
  "ProMaster Cargo Van",
  "ProMaster City",
  "ProMaster Window Van",
  "R1S",
  "R1T",
  "Cullinan",
  "Dawn",
  "Ghost",
  "Phantom",
  "Wraith",
  "9-2X",
  "9-3",
  "9-4X",
  "9-5",
  "9-7X",
  "900",
  "9000",
  "Astra",
  "Aura",
  "Ion",
  "L-Series",
  "Outlook",
  "Relay",
  "S-Series",
  "SKY",
  "VUE",
  "FR-S",
  "iA",
  "iM",
  "iQ",
  "tC",
  "xA",
  "xB",
  "xD",
  "fortwo",
  "fortwo cabrio",
  "fortwo electric drive",
  "fortwo electric drive cabrio",
  "fortwo EQ cabrio",
  "fortwo EQ coupe",
  "Viper",
  "Ascent",
  "B9 Tribeca",
  "Baja",
  "BRZ",
  "Crosstrek",
  "Forester",
  "Impreza",
  "Justy",
  "Legacy",
  "Loyale",
  "Outback",
  "Solterra",
  "SVX",
  "Tribeca",
  "WRX",
  "XV Crosstrek",
  "Aerio",
  "Equator Crew Cab",
  "Equator Extended Cab",
  "Esteem",
  "Forenza",
  "Grand Vitara",
  "Kizashi",
  "Reno",
  "Samurai",
  "Sidekick",
  "Swift",
  "SX4",
  "Verona",
  "Vitara",
  "X-90",
  "XL-7",
  "XL7",
  "Cybertruck",
  "Model 3",
  "Model S",
  "Model X",
  "Model Y",
  "4Runner",
  "86",
  "Avalon",
  "Avalon Hybrid",
  "bZ4X",
  "C-HR",
  "Camry",
  "Camry Hybrid",
  "Celica",
  "Corolla",
  "Corolla Cross",
  "Corolla Cross Hybrid",
  "Corolla Hatchback",
  "Corolla Hybrid",
  "Corolla iM",
  "Cressida",
  "Crown",
  "Crown Signia",
  "Echo",
  "FJ Cruiser",
  "GR Corolla",
  "GR Supra",
  "GR86",
  "Grand Highlander",
  "Grand Highlander Hybrid",
  "Highlander",
  "Highlander Hybrid",
  "Land Cruiser",
  "Matrix",
  "Mirai",
  "MR2",
  "Paseo",
  "Previa",
  "Prius",
  "Prius c",
  "Prius Plug-in Hybrid",
  "Prius Prime",
  "Prius v",
  "RAV4",
  "RAV4 Hybrid",
  "RAV4 Prime",
  "Regular Cab",
  "Sequoia",
  "Sienna",
  "Solara",
  "Supra",
  "T100 Regular Cab",
  "T100 Xtracab",
  "Tacoma Access Cab",
  "Tacoma Double Cab",
  "Tacoma Regular Cab",
  "Tacoma XtraCab",
  "Tercel",
  "Tundra Access Cab",
  "Tundra CrewMax",
  "Tundra Double Cab",
  "Tundra Hybrid CrewMax",
  "Tundra Regular Cab",
  "Venza",
  "Xtra Cab",
  "Yaris",
  "Yaris Hatchback",
  "Yaris iA",
  "VF 6",
  "VF 7",
  "VF 8",
  "VF 9",
  "Arteon",
  "Atlas",
  "Atlas Cross Sport",
  "Beetle",
  "Cabrio",
  "Cabrio (New)",
  "Cabriolet",
  "CC",
  "Corrado",
  "e-Golf",
  "Eos",
  "Eurovan",
  "Fox",
  "GLI",
  "Golf",
  "Golf (New)",
  "Golf Alltrack",
  "Golf GTI",
  "Golf III",
  "Golf R",
  "Golf SportWagen",
  "GTI",
  "GTI (New)",
  "ID.4",
  "ID.7",
  "ID.Buzz",
  "Jetta",
  "Jetta (New)",
  "Jetta GLI",
  "Jetta III",
  "Jetta SportWagen",
  "New Beetle",
  "Passat",
  "Passat (New)",
  "Phaeton",
  "R32",
  "Rabbit",
  "Routan",
  "Taos",
  "Tiguan",
  "Tiguan Limited",
  "Touareg",
  "Touareg 2",
  "240",
  "740",
  "850",
  "940",
  "960",
  "C30",
  "C40 Recharge",
  "C70",
  "EX30",
  "EX90",
  "S40",
  "S40 (New)",
  "S60",
  "S70",
  "S80",
  "S90",
  "V40",
  "V50",
  "V60",
  "V70",
  "V90",
  "XC40",
  "XC40 Recharge",
  "XC60",
  "XC70",
  "XC90",
];

const colorList = [
  "Beige",
  "Black",
  "Blue",
  "Brown",
  "Burgundy",
  "Charcoal",
  "Gold",
  "Green",
  "Grey",
  "Off white",
  "Orange",
  "Pink",
  "Purple",
  "Red",
  "Silver",
  "Tan",
  "Turquoise",
  "White",
  "Yellow",
];
export { variantList, makeList, modelList, colorList };
