import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  inventoryData: [
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
  ],
};

export const inventorySlice = createSlice({
  name: "inventory",
  initialState,
  reducers: {
    deleteInventory: (state, action) => {
      state.inventoryData.splice(action.payload, 1);
      state.showDeleteInventoryModal = true;
    },
  },
});

export const { deleteInventory } = inventorySlice.actions;
export default inventorySlice.reducer;
