import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  inventoryData: [
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
    {
      sku: 1,
      part: "Alternator",
      year: "2022-2024",
      model: "Alfa Romeo",
      make: "Alfa Romeo",
      variant: "Frot-Mirror",
    },
  ],
  showActionMenu: false,
  showDeleteInventoryModal: false,
  deleteInventoryIndex: -1,
  showInventorySideMenu: {
    value: false,
    mode: "add",
  },
  showSuccessModal: false,
};

export const inventorySlice = createSlice({
  name: "inventory",
  initialState,
  reducers: {
    deleteInventory: (state, action) => {
      state.inventoryData.splice(action.payload, 1);
      state.showDeleteInventoryModal = true;
    },
    setDeleteInventoryIndex: (state, action) => {
      state.deleteInventoryIndex = action.payload;
    },
    setShowDeleteInventoryModal: (state, action) => {
      state.showDeleteInventoryModal = action.payload;
    },
    setShowInventorySideMenu: (state, action) => {
      state.showInventorySideMenu = action.payload;
    },
    setShowSuccessModal: (state, action) => {
      state.showSuccessModal = action.payload;
    },
  },
});

export const {
  deleteInventory,
  setDeleteInventoryIndex,
  setShowDeleteInventoryModal,
  setShowInventorySideMenu,
  setShowSuccessModal,
} = inventorySlice.actions;
export default inventorySlice.reducer;
